/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Braya
 */
public class table extends javax.swing.JFrame {

    public static final String URL = "jdbc:mysql://localhost:3306/university_for_u";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "";
    public int rows=0;
    public table() {
        initComponents();
        Iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtstudiantes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Addbutton = new javax.swing.JButton();
        Alv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "email", "pass", "genre", "0"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtstudiantes);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Addbutton.setText("New");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        Alv.setText("ALv");
        Alv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Addbutton)
                        .addGap(90, 90, 90)
                        .addComponent(Alv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Addbutton)
                    .addComponent(Alv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ras=0;

        //conexion
        try {
            for (int i = rows; i < jtstudiantes.getRowCount(); i++) {
                
                Connection con = null;
                con = getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO usuarios (name,email,pass,genre) Values (?,?,?,?)");
                System.out.println(jtstudiantes.getRowCount()+"sdads");
            System.out.println((String) jtstudiantes.getValueAt(i, 0));
            System.out.println((String) jtstudiantes.getValueAt(i, 1));
            System.out.println((String) jtstudiantes.getValueAt(i, 2));
            System.out.println((String) jtstudiantes.getValueAt(i, 3));
            ps.setString(1, (String) jtstudiantes.getValueAt(i, 0));
            ps.setString(2, (String) jtstudiantes.getValueAt(i, 1));
            ps.setString(3, (String) jtstudiantes.getValueAt(i, 2));
            ps.setString(4, (String) jtstudiantes.getValueAt(i, 3));

            
            
            

            ras = ps.executeUpdate();
            con.close();
            }
            
            if (ras > 0) {
                JOptionPane.showMessageDialog(null, "wardado");
            } else {
                JOptionPane.showMessageDialog(null, "no wrdado");
            }
            

        } catch (Exception ex) {
            Logger.getLogger(table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jtstudiantes.getModel();
        model.addRow(new Object[jtstudiantes.getRowCount()]);
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void AlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlvActionPerformed
         Connection con = null;
        con = getConnection();
        PreparedStatement ps;
       
        
        //conexion
        try {
            ps = con.prepareStatement("DELETE FROM usuarios");
            int ras = ps.executeUpdate("DELETE FROM usuarios");
            con.close();

        } catch (Exception ex) {
            Logger.getLogger(table.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AlvActionPerformed

    public void Iniciar()
    {
        Connection con = null;
        con = getConnection();
        PreparedStatement ps;
        ResultSet res;
        
        //conexion
        try {
            ps = con.prepareCall("SELECT * FROM usuarios");
            res = ps.executeQuery();
            int i=0;
                while (res.next()) {
                DefaultTableModel model = (DefaultTableModel) jtstudiantes.getModel();
                model.addRow(new Object[jtstudiantes.getRowCount()]);
                model.setValueAt(res.getString("name"), i, 0);
                model.setValueAt(res.getString("email"), i, 1);
                model.setValueAt(res.getString("pass"), i, 2);
                model.setValueAt(res.getString("genre"), i, 3);
                rows++;
                i++;
                }
              
            

            con.close();

        } catch (Exception ex) {
            Logger.getLogger(table.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static Connection getConnection() {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
            
        } catch (Exception ex) {
            Logger.getLogger(table.class.getName()).log(Level.SEVERE, null, ex);
        }
        return con;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JButton Alv;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtstudiantes;
    // End of variables declaration//GEN-END:variables
}
